TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += pt2025.db
DATA += pt2025.proto

#=======================================
include $(TOP)/configure/RULES
